{"name": "test_vs_file_upload[kyle-123456]", "status": "broken", "statusDetails": {"message": "TypeError: unsupported callable", "trace": "func = <classmethod object at 0x000002904E3AE358>\n\n    def getfullargspec(func):\n        \"\"\"Get the names and default values of a callable object's parameters.\n    \n        A tuple of seven things is returned:\n        (args, varargs, varkw, defaults, kwonlyargs, kwonlydefaults, annotations).\n        'args' is a list of the parameter names.\n        'varargs' and 'varkw' are the names of the * and ** parameters or None.\n        'defaults' is an n-tuple of the default values of the last n parameters.\n        'kwonlyargs' is a list of keyword-only parameter names.\n        'kwonlydefaults' is a dictionary mapping names from kwonlyargs to defaults.\n        'annotations' is a dictionary mapping parameter names to annotations.\n    \n        Notable differences from inspect.signature():\n          - the \"self\" parameter is always reported, even for bound methods\n          - wrapper chains defined by __wrapped__ *not* unwrapped automatically\n        \"\"\"\n    \n        try:\n            # Re: `skip_bound_arg=False`\n            #\n            # There is a notable difference in behaviour between getfullargspec\n            # and Signature: the former always returns 'self' parameter for bound\n            # methods, whereas the Signature always shows the actual calling\n            # signature of the passed object.\n            #\n            # To simulate this behaviour, we \"unbind\" bound methods, to trick\n            # inspect.signature to always return their first parameter (\"self\",\n            # usually)\n    \n            # Re: `follow_wrapper_chains=False`\n            #\n            # getfullargspec() historically ignored __wrapped__ attributes,\n            # so we ensure that remains the case in 3.3+\n    \n            sig = _signature_from_callable(func,\n                                           follow_wrapper_chains=False,\n                                           skip_bound_arg=False,\n>                                          sigcls=Signature)\n\nC:\\Users\\14546\\AppData\\Local\\Programs\\Python\\Python36\\lib\\inspect.py:1126: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nobj = <classmethod object at 0x000002904E3AE358>\n\n    def _signature_from_callable(obj, *,\n                                 follow_wrapper_chains=True,\n                                 skip_bound_arg=True,\n                                 sigcls):\n    \n        \"\"\"Private helper function to get signature for arbitrary\n        callable objects.\n        \"\"\"\n    \n        if not callable(obj):\n>           raise TypeError('{!r} is not a callable object'.format(obj))\nE           TypeError: <classmethod object at 0x000002904E3AE358> is not a callable object\n\nC:\\Users\\14546\\AppData\\Local\\Programs\\Python\\Python36\\lib\\inspect.py:2193: TypeError\n\nThe above exception was the direct cause of the following exception:\n\nself = <scripts.test_vs_file_upload.TestVsFileUpload object at 0x000002904EEE3240>\nusername = 'kyle', password = '123456'\n\n    @pytest.mark.parametrize(\"username,password\", read_yaml(\"vs_file_upload.yaml\"))\n    def test_vs_file_upload(self, username, password):\n>       self.vs.page_vs_file_upload(username, password)\n\ntest_vs_file_upload.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\page\\page_vs_file_upload.py:35: in page_vs_file_upload\n    page.page_vs_login.PageVsLogin.page_input_username(username)\n..\\venv\\lib\\site-packages\\allure_commons\\utils.py:308: in func_parameters\n    arg_spec = getargspec(func) if six.PY2 else inspect.getfullargspec(func)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfunc = <classmethod object at 0x000002904E3AE358>\n\n    def getfullargspec(func):\n        \"\"\"Get the names and default values of a callable object's parameters.\n    \n        A tuple of seven things is returned:\n        (args, varargs, varkw, defaults, kwonlyargs, kwonlydefaults, annotations).\n        'args' is a list of the parameter names.\n        'varargs' and 'varkw' are the names of the * and ** parameters or None.\n        'defaults' is an n-tuple of the default values of the last n parameters.\n        'kwonlyargs' is a list of keyword-only parameter names.\n        'kwonlydefaults' is a dictionary mapping names from kwonlyargs to defaults.\n        'annotations' is a dictionary mapping parameter names to annotations.\n    \n        Notable differences from inspect.signature():\n          - the \"self\" parameter is always reported, even for bound methods\n          - wrapper chains defined by __wrapped__ *not* unwrapped automatically\n        \"\"\"\n    \n        try:\n            # Re: `skip_bound_arg=False`\n            #\n            # There is a notable difference in behaviour between getfullargspec\n            # and Signature: the former always returns 'self' parameter for bound\n            # methods, whereas the Signature always shows the actual calling\n            # signature of the passed object.\n            #\n            # To simulate this behaviour, we \"unbind\" bound methods, to trick\n            # inspect.signature to always return their first parameter (\"self\",\n            # usually)\n    \n            # Re: `follow_wrapper_chains=False`\n            #\n            # getfullargspec() historically ignored __wrapped__ attributes,\n            # so we ensure that remains the case in 3.3+\n    \n            sig = _signature_from_callable(func,\n                                           follow_wrapper_chains=False,\n                                           skip_bound_arg=False,\n                                           sigcls=Signature)\n        except Exception as ex:\n            # Most of the times 'signature' will raise ValueError.\n            # But, it can also raise AttributeError, and, maybe something\n            # else. So to be fully backwards compatible, we catch all\n            # possible exceptions here, and reraise a TypeError.\n>           raise TypeError('unsupported callable') from ex\nE           TypeError: unsupported callable\n\nC:\\Users\\14546\\AppData\\Local\\Programs\\Python\\Python36\\lib\\inspect.py:1132: TypeError"}, "attachments": [{"name": "log", "source": "ae7c4164-a5e3-4b1c-abb0-212f6ab53c1c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'kyle'"}, {"name": "password", "value": "'123456'"}], "start": 1636095827755, "stop": 1636095827755, "uuid": "ed7fad16-8282-47ff-9cb7-9ee69962cf8e", "historyId": "2893db048a7a4a36c7223dd259aa7499", "testCaseId": "f39192183e51c0ff0db3c4a624ea14dd", "fullName": "scripts.test_vs_file_upload.TestVsFileUpload#test_vs_file_upload", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_vs_file_upload"}, {"name": "subSuite", "value": "TestVsFileUpload"}, {"name": "host", "value": "LAPTOP-2MM4SIL7"}, {"name": "thread", "value": "18048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_vs_file_upload"}]}