{"uuid": "bc17aef9-2f6e-4b88-8259-fe4a4c4666a5", "children": ["27886855-1e7d-4420-90c5-561f686e269b"], "befores": [{"name": "xunit_setup_class_fixture_TestVsFileUpload", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=95.0.4638.69)\n\n", "trace": "  File \"D:\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\PycharmProjects\\EXDUIAutoTest\\scripts\\test_vs_file_upload.py\", line 21, in setup_class\n    driver = GetDriver.get_web_driver(page.url_vs)\n  File \"D:\\PycharmProjects\\EXDUIAutoTest\\tools\\get_driver.py\", line 19, in get_web_driver\n    cls.__web_driver.get(url)\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1638165832823, "stop": 1638165864860}], "start": 1638165832823, "stop": 1638165865056}